# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    knowledge.upload_dir: '%kernel.project_dir%/public/uploads/knowledge'
    knowledge.image_dir: '%knowledge.upload_dir%/images'
    knowledge.document_dir: '%knowledge.upload_dir%/documents'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Knowledge\Service\ImageUploader:
        arguments:
            $knowledgeUploadDir: '%knowledge.upload_dir%'